ci:
  submodules: true
  skip: [manpage-syntax]
repos:
# General file hygiene
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: check-json
# Validate repository-wide whitespace and indentation against .editorconfig
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 3.11.1
  hooks:
  - id: editorconfig-checker
    alias: ec
# Format shell scripts according to .editorconfig rules
- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.14.1-1
  hooks:
  - id: shfmt
# Static analysis for Bash / shell script bugs and style warnings
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.11.0.1
  hooks:
  - id: shellcheck
    exclude: '^LICENSE$'
- repo: local
  hooks:
  - id: manpage-syntax
    name: Man page syntax check
    entry: sh -c 'for file do groff -man -Tutf8 -z "$file" >/dev/null; done' --
    language: system
    files: '^man/.*$'
  - id: cleanup-branches-bats-tests
    name: cleanup-branches Tests
    entry: test/bats-precommit-wrapper
    language: node
    additional_dependencies:
    - bats@1.11.0
    files: cleanup-branches
  - id: diff-commits-bats-tests
    name: diff-commits Tests
    entry: test/bats-precommit-wrapper
    language: node
    additional_dependencies:
    - bats@1.11.0
    files: diff-commits
  - id: diff-staged-vs-bats-tests
    name: diff-staged-vs Tests
    entry: test/bats-precommit-wrapper
    language: node
    additional_dependencies:
    - bats@1.11.0
    files: diff-staged-vs
  - id: find-time-travellers-bats-tests
    name: find-time-travellers Tests
    entry: test/bats-precommit-wrapper
    language: node
    additional_dependencies:
    - bats@1.11.0
    files: find-time-travellers
  - id: pull-branches-bats-tests
    name: pull-branches Tests
    entry: test/bats-precommit-wrapper
    language: node
    additional_dependencies:
    - bats@1.11.0
    files: pull-branches
  - id: status-push-bats-tests
    name: status-push Tests
    entry: test/bats-precommit-wrapper
    language: node
    additional_dependencies:
    - bats@1.11.0
    files: status-push
  - id: update-remote-branches-bats-tests
    name: update-remote-branches Tests
    entry: test/bats-precommit-wrapper
    language: node
    additional_dependencies:
    - bats@1.11.0
    files: update-remote-branches
