#!/usr/bin/env sh

trap 'rm -rf "$tmp_dir"' EXIT
tmp_dir=$(mktemp -d)

git show --format=fuller "$1" >"$tmp_dir/$1"
git show --format=fuller "$2" >"$tmp_dir/$2"

git difftool --no-index "$tmp_dir/$1" "$tmp_dir/$2"
