#!/usr/bin/env sh

refname=${1:-REBASE_HEAD}

trap 'rm -rf "$tmp_dir"' EXIT
tmp_dir=$(mktemp -d)

git show --format=fuller "${refname}" > "$tmp_dir/${refname}"
git diff --staged > "$tmp_dir/staged"

# This script compares the staged patch with the patch from a specified commit (defaulting
# to REBASE_HEAD if no commit is provided).  It is useful for reviewing changes during a
# rebase.  It can be installed as a git subcommand named "git diff-staged-vs" by placing
# it in your PATH.
git difftool --no-index "$tmp_dir/${refname}" "$tmp_dir/staged"
