name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Check man page syntax
        run: find man -type f -exec groff -man -Tutf8 -z "{}" \;

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: shellcheck --shell=bash git-* test/*bats*

      - name: Setup Bats
        uses: bats-core/bats-action@4.0.0

      - name: Run tests
        run: bats test --print-output-on-failure
